FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y \
  build-essential \
  libxml2-dev \
  r-base \
  r-base-dev \
  libuv1-dev \
  git-lfs